### ISSUE TITLE
Source Link does not appear to work as expected

### ISSUE THREAD

**Issue by rheone** [sandialabs/Arcus#13]
Source is not available in Visual Studio 2019 community edition.

**Comment by rheone** [comment]
This may be a side effect of the way the nuget packages were originally built and released, and may have resolved itself now that we have an appropriate GitHub hash associated.

Verify, but note to self don't pack from internal repository

**Comment by ahsteele** [comment]
What do we need to do to verify this is resolved?

**Comment by rheone** [comment]
My approach would be to build and make a nuget package from the master branch (even locally) with the last commit being to the GitHub origin master having the .git folder in tact. We'd then

 - Verify that the a compiler warning isn't issued (something that was not noticed before)
 - Peek into the .nupack & .nuspec (they're zips) for the appropriate urls, (not sure what I'm looking for just yet honestly)
 - Lastly consume the package locally as a dependency in a temp project and verifying that the source link seems to be working.

I don't know if this is the best approach, but it would in my estimate be a telling one.

**Comment by rheone** [comment]
This issue seems to be resolved, and should be covered in the next release by our current build pipeline.
