### ISSUE TITLE
Shield for Azure DevOps shield is broken in readme screen.

### ISSUE THREAD

**Issue by ahsteele** [sandialabs/Arcus#30]
# Describe the bug

![image](https://user-images.githubusercontent.com/428747/68339418-c3a00400-00a1-11ea-8d81-f0a3b7501c9a.png)

# Expected behavior

For the shield to not be borked so frequently

# Example of how to Reproduce

Load the readme in GitHub

**Comment by rheone** [comment]
@nicksterx you've set this up, might it have something to do with the server not waking up on time? Is there a work around, or should drop the badge and look into some sort of replacement?

**Comment by nicksterx** [comment]
This looks like an error with shields.io timing out when it is loading that badge. Looking into alternatives before we remove it. 
https://github.com/badges/shields/issues/1568

**Comment by nicksterx** [comment]
https://badgen.net/ seems like it might be an alternative. But looking at other projects they don't have the test/coverage badges. I'm thinking we should drop them?
