### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by ahsteele** [sandialabs/Arcus#6]
Readme should include the Arcus icon and link to Gulliver. Also the copyright notice is in a code block and looks ugly. License might also be code and need to change too.

**Comment by rheone** [comment]
Also include gitter.im chat link [![Join the chat at https://gitter.im/sandialabs/Arcus](https://badges.gitter.im/sandialabs/Arcus.svg)](https://gitter.im/sandialabs/Arcus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```
[![Join the chat at https://gitter.im/sandialabs/Arcus](https://badges.gitter.im/sandialabs/Arcus.svg)](https://gitter.im/sandialabs/Arcus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```
